stages:
  data_ingestion:
    cmd: python src/Cauliflower_Classifier/pipeline/stage_01_data_ingestion.py
    deps: 
      - src/Cauliflower_Classifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/dataset

  prepare_base_model:
    cmd: python src/Cauliflower_Classifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/Cauliflower_Classifier/pipeline/stage_02_prepare_base_model.py
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/Cauliflower_Classifier/pipeline/stage_03_model_training.py
    deps:
      - src/Cauliflower_Classifier/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/dataset
      - artifacts/prepare_base_model
    params:
      - EPOCHS
      - BATCH_SIZE
      - IMAGE_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python src/Cauliflower_Classifier/pipeline/stage_04_model_evaluation_mlflow.py
    deps:
      - src/Cauliflower_Classifier/pipeline/stage_04_model_evaluation_mlflow.py
      - config/config.yaml
      - artifacts/data_ingestion/dataset
      - artifacts/training/model.h5
    params:
      - BATCH_SIZE
      - IMAGE_SIZE
    metrics:
      - scores.json:
          cache: false
